export type IconName =
  | "edit"
  | "delete"
  | "color"
  | "grip-lines"
  | "play"
  | "pause"
  | "exit"
  | "project-list"
  | "create-project"
  | "create-action"
  | "action-list"
  | "statistics"
  | "application-settings"
  | "finish"
  | "elapsed-time"
  | "details"
  | "back";
