import { IconName } from "./IconName";

export const iconMap = new Map<IconName, string>()
  .set("delete", "trash")
  .set("color", "paint-brush")
  .set("exit", "sign-out-alt")
  .set("project-list", "list")
  .set("create-project", "file-alt")
  .set("create-activity", "file")
  .set("activity-list", "tags")
  .set("statistics", "chart-bar")
  .set("application-settings", "cog")
  .set("finish", "flag-checkered")
  .set("elapsed-time", "clock")
  .set("details", "eye")
  .set("back", "arrow-left")
  .set("menu", "bars")
  .set("info", "info-circle")
  .set("home-page", "house-user")
  .set("add", "plus");
